[package]
name    = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow       = { workspace = true }
indexmap     = { workspace = true, features = ["serde"] }
quote        = { workspace = true }
serde        = { workspace = true, features = ["derive"] }
serde_json   = { workspace = true, features = ["preserve_order"] }
prettyplease = { workspace = true }
project-root = { workspace = true }
syn          = { workspace = true }
proc-macro2  = { workspace = true }
time         = { workspace = true, features = ["formatting", "macros", "parsing"] }
