[package]
name    = "xtask"
version = "0.1.0"
edition = "2021"
publish = false

[lints]
workspace = true

[dependencies]
anyhow       = "1.0"
indexmap     = { version = "2.1", features = ["serde"] }
quote        = "1.0"
serde        = { version = "1.0", features = ["derive"] }
serde_json   = { version = "1.0", features = ["preserve_order"] }
prettyplease = "0.2.20"
project-root = "0.2.2"
syn          = "2"
proc-macro2  = "1.0.84"
rkyv         = "0.7.44"
time         = { version = "0.3.36", features = ["formatting", "macros", "parsing"] }
