name: Miri

permissions: {}

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "src/**"
      - ".github/workflows/miri.yml"
  push:
    branches:
      - main
    paths:
      - "src/**"
      - ".github/workflows/miri.yml"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  miri:
    name: Miri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@b13d20b7cda4e2f325ef19895128f7ff735c0b3d # v1.3.1

      - uses: oxc-project/setup-rust@c8224157c0bf235aabc633e8cd50d344f087a7de # v1.0.12
        with:
          cache-key: miri
          save-cache: ${{ github.ref_name == 'main' }}

      - uses: oxc-project/setup-node@141eb77546de6702f92d320926403fe3f9f6a6f2 # v1.0.5

      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup

      # `--lib --bins --tests` omits doctests, which Miri can't run
      # https://github.com/oxc-project/oxc/pull/11092
      - name: Test with Miri
        run: |
          cargo miri test --lib --bins --tests --all-features
        env:
          MIRIFLAGS: -Zmiri-disable-isolation
